# Starter pipeline for esy-based projects
# Start with a minimal pipeline that you can customize to build and deploy your code.

name: $(Build.SourceVersion)
jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - script: sudo apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libegl1-mesa-dev mesa-utils mesa-utils-extra ragel
  - template: .ci/esy-build-steps.yml

- job: MacOS
  pool:
    vmImage: 'macOS 10.14'
  steps:
  - script: brew install libpng
  - template: .ci/esy-build-steps.yml

- job: Windows
  timeoutInMinutes: 120
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: .ci/esy-build-steps.yml
